import site from "../config/site.mjs";
import {escapeHtml as e, escapeJson, safeUrl, postPath, pagePath, dateLabel, readingMinutes, sampleMessage} from "./content.mjs";
export const names={en:{research:"Research",engineering:"Engineering",notes:"Notes"},ja:{research:"研究",engineering:"実装",notes:"ノート"}};
const icons={search:'<circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.4 1.4m11.2 11.2L19 19M5 19l1.4-1.4M17.6 6.4 19 5"/>',arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',external:'<path d="M8 5H5v14h14v-3M12 5h7v7M10 14l9-9"/>',moon:'<path d="M20.5 14a8.8 8.8 0 0 1-10.5-10.5A8.8 8.8 0 1 0 20.5 14Z"/>'};
export function icon(name) {return `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]??icons.arrow}</svg>`;}
/** @param {{title?:string,description?:string,path?:string,lang?:string,sample?:boolean,post?:any,other?:any}} options */
export function headMeta({title=site.title,description=site.description,path="/",lang="en",sample=false,post=null,other=null}={}) {
 const canonical=new URL(path,site.url).href;
 const d=post?.data??post;
 const og=d?.ogImage??(d?`/og/posts/${d.lang}-${d.slug}.png`:"/og/default.png");
 const index=site.stage==="preview"||sample||path.includes("/search/")||path.includes("/lab/")||path==="/404/";
 const json=d?{"@context":"https://schema.org","@type":"BlogPosting",headline:d.title,description:d.description,datePublished:new Date(d.pubDatetime).toISOString(),...(d.modDatetime?{dateModified:new Date(d.modDatetime).toISOString()}:{}),author:{"@type":"Person",name:site.title,url:site.url},mainEntityOfPage:canonical,image:new URL(og,site.url).href,inLanguage:lang}:{"@context":"https://schema.org","@type":"WebSite",name:site.title,url:site.url};
 return `<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title===site.title?title:title+" · "+site.title)}</title><meta name="description" content="${e(description)}"><meta name="author" content="${e(site.title)}"><meta name="robots" content="${index?"noindex, nofollow":"index, follow"}"><link rel="canonical" href="${e(canonical)}"><link rel="icon" type="image/svg+xml" href="/favicon.svg"><link rel="alternate" type="application/rss+xml" title="${e(site.title)}" href="/rss.xml"><meta name="theme-color" content="#fafaf8"><meta property="og:type" content="${d?"article":"website"}"><meta property="og:locale" content="${lang==='ja'?'ja_JP':'en_US'}"><meta property="og:site_name" content="${e(site.title)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(canonical)}"><meta property="og:image" content="${e(new URL(og,site.url).href)}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image">${other?`<link rel="alternate" hreflang="${lang}" href="${e(canonical)}"><link rel="alternate" hreflang="${other.lang}" href="${e(new URL(other.path,site.url).href)}">`:""}<script type="application/ld+json">${escapeJson(json)}</script>`;
}
export const themeInit=`(()=>{let theme;try{theme=localStorage.getItem('kanta-theme')}catch{}if(theme!=='light'&&theme!=='dark')theme=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.dataset.theme=theme;document.documentElement.style.colorScheme=theme;})()`;
export function header(path="/",lang="en") {
 const ja=lang==='ja';
 const links=[["writing",ja?"記事":"Writing"],["about",ja?"紹介":"About"]];
 const nav=links.map(([slug,label])=>`<a href="${pagePath(slug,lang)}"${path.includes('/'+slug+'/')?' aria-current="page"':''}>${label}</a>`).join("");
 return `<a class="skip-link" href="#main">${ja?"本文へ移動":"Skip to content"}</a><header class="site-header wrap"><a class="wordmark" href="${pagePath('',lang)}">Kanta Hayashi</a><div class="header-right"><nav class="desktop-nav" aria-label="${ja?"メイン":"Main"}">${nav}</nav><a class="icon-button" href="${pagePath('search',lang)}" aria-label="${ja?"検索":"Search"}">${icon('search')}</a><button type="button" class="icon-button theme-toggle" aria-label="${ja?"配色を切り替え":"Toggle color theme"}" aria-pressed="false"><span class="theme-sun">${icon('sun')}</span><span class="theme-moon">${icon('moon')}</span></button><details class="mobile-nav"><summary>${ja?"メニュー":"Menu"}<span aria-hidden="true">⌄</span></summary><nav aria-label="${ja?"モバイル":"Mobile"}">${nav}</nav></details></div></header>`;
}
export function footer(lang="en") {
 const ja=lang==='ja';
 return `<footer class="site-footer wrap"><nav class="footer-links" aria-label="${ja?'フッター':'Footer'}"><a href="${site.github}">GitHub</a><a href="/rss.xml">RSS</a><a href="${ja?'/':'/ja/'}" lang="${ja?'en':'ja'}">${ja?'English':'日本語'}</a>${site.stage==='preview'?`<a href="${pagePath('lab',lang)}">${ja?'表示チェック':'Test pages'}</a>`:''}</nav><div class="colophon"><span>© ${site.copyrightYear} Kanta Hayashi</span><span>Based on <a href="https://github.com/satnaing/astro-paper">AstroPaper</a></span></div></footer>`;
}
export function previewNotice(lang="en") {
 if(site.stage!=="preview")return "";
 const ja=lang==='ja';
 return `<aside class="preview-banner wrap" aria-label="${ja?'プレビュー':'Preview'}"><span>${ja?'プレビュー：以下はすべて表示確認用のテスト記事です。':'Preview — these are test posts, not published work.'}</span><a href="${pagePath('lab',lang)}">${ja?'チェック項目':'Checklist'} ↗</a></aside>`;
}
export function meta(post,lang="en") {
 const d=post.data??post;return `<div class="post-meta"><span class="eyebrow">${e(names[lang][d.kind])}</span><span class="meta-dot">/</span><time datetime="${new Date(d.pubDatetime).toISOString()}">${dateLabel(d.pubDatetime,lang)}</time><span class="meta-dot">/</span><span>${readingMinutes(post.body??"")} ${lang==="ja"?"分":"min read"}</span>${d.sample?`<span class="sample-badge">${lang==="ja"?"テスト記事":"Test post"}</span>`:""}${d.lang!==lang?`<span class="language-badge">${d.lang==='ja'?'日本語':'EN'}</span>`:""}</div>`;
}
export function postCard(post,lang="en",featured=false) {
 const d=post.data??post;
 return `<article class="post-row" data-kind="${e(d.kind)}" data-lang="${e(d.lang)}" data-tags="${e(JSON.stringify(d.tags))}">${meta(post,lang)}<h3><a href="${postPath(post)}">${e(d.title)}</a></h3><p>${e(d.description)}</p></article>`;
}
export function home(posts,lang="en") {
 const ja=lang==='ja';
 const local=posts.filter(p=>p.data.lang===lang);
 const display=(local.length?local:posts).slice(0,6);
 return `<main id="main"><section class="intro wrap"><h1>${ja?'言語モデルと、その周り。':'Language models & other notes.'}</h1><p>${ja?'LLMについて考え中……':'Thinking about LLMs.'}</p><div class="intro-links"><a href="${site.github}">GitHub ↗</a><a href="/rss.xml">RSS</a><a href="${pagePath('about',lang)}">${ja?'自己紹介':'About me'}</a></div></section>${previewNotice(lang)}<section class="writing-section wrap" aria-labelledby="recent-heading"><div class="section-heading"><h2 id="recent-heading">${ja?'最近の記事':'Recent posts'}</h2><a href="${pagePath('writing',lang)}">${ja?'すべての記事':'All posts'} ↗</a></div><div class="post-list">${display.map(p=>postCard(p,lang)).join('')}</div>${display.length?'':`<p class="empty-state">${ja?'最初の記事を準備中です。':'No published posts yet.'}</p>`}</section></main>`;
}
export function writing(posts,lang="en") {
 const ja=lang==='ja';return `<main id="main" class="wrap page-main"><div class="page-intro"><h1>${ja?'記事':'Writing'}</h1><p>${ja?'研究の記録、実装の話、まだ名前のない考え。':'Experiments, implementation notes, and occasional detours.'}</p></div>${site.stage==='preview'?`<p class="inline-notice">${ja?'この一覧は表示確認用のテスト記事です。':'This preview contains test articles, not published research.'}</p>`:''}<nav class="filters" aria-label="${ja?'記事の種類':'Filter writing'}">${[['all',ja?'すべて':'All'],...Object.entries(names[lang])].map(([k,v])=>`<button type="button" data-filter="${k}" aria-pressed="${k==='all'}">${v}</button>`).join('')}</nav><p class="filter-status sr-only" role="status"></p><div class="post-list">${posts.map(p=>postCard(p,lang)).join('')}</div><p class="no-posts" hidden>${ja?'該当する記事はありません。':'No notes in this category yet.'}</p></main>`;
}
/** @param {any} post @param {any[]} headings @param {any} other */
export function articleStart(post,headings=[],other=null) {
 const d=post.data??post,lang=d.lang; const ja=lang==='ja';
 const refs=[['code','Code'],['paper','Paper'],['data','Data']].filter(([k])=>d[k]);
 return `<main id="main" class="post-main"><header class="post-header"><a class="back-link" href="${pagePath('writing',lang)}">← ${ja?'記事一覧':'All writing'}</a>${meta(post,lang)}<h1 data-pagefind-meta="title">${e(d.title)}</h1><p class="post-description" data-pagefind-meta="description">${e(d.description)}</p><div class="post-byline"><span>${e(d.author??site.title)}</span>${d.modDatetime?`<span> · ${ja?'更新':'Updated'} ${dateLabel(d.modDatetime,lang)}</span>`:''}${other?`<a class="translation-link" href="${postPath(other)}" lang="${other.data.lang}">${other.data.lang==='ja'?'日本語で読む':'Read in English'} ↗</a>`:''}</div>${refs.length?`<div class="resource-links">${refs.map(([k,label])=>`<a href="${e(safeUrl(d[k]))}">${label} ↗</a>`).join('')}</div>`:''}${d.sample?`<aside class="sample-notice" data-pagefind-ignore><strong>${ja?'テスト記事':'Test article'}</strong><p>${sampleMessage(lang)} ${ja?'RSSには配信されません。':'Not included in RSS.'}</p></aside>`:''}</header><div class="article-grid"><aside class="toc" aria-label="${ja?'目次':'Table of contents'}" data-pagefind-ignore><details><summary>${ja?'このページ':'On this page'}</summary><ol>${headings.filter(h=>h.depth===2||h.depth===3).map(h=>`<li class="depth-${h.depth}"><a href="#${e(h.slug)}">${e(h.text)}</a></li>`).join('')}</ol></details></aside><article class="prose" lang="${lang}" data-pagefind-body data-pagefind-filter="kind:${e(names.en[d.kind])}">`;
}
export function articleEnd(post,related=[]) {
 const d=post.data??post,ja=d.lang==='ja';return `</article></div><footer class="post-end"><div class="tags">${d.tags.map(t=>`<a href="${pagePath('writing',d.lang)}?tag=${encodeURIComponent(t)}">${e(t)}</a>`).join('')}</div><div class="post-end-row"><a href="${pagePath('writing',d.lang)}">← ${ja?'記事一覧へ':'Back to writing'}</a><a href="#main">${ja?'上へ':'Back to top'} ↑</a></div>${related.length?`<h2>${ja?'次のノート':'Keep reading'}</h2>${related.slice(0,2).map(p=>postCard(p,d.lang)).join('')}`:''}</footer></main>`;
}
export function searchPage(lang='en') {
 const ja=lang==='ja';return `<main id="main" class="wrap page-main"><div class="page-intro"><h1>${ja?'検索':'Search'}</h1><p>${ja?'タイトル、本文、タグから探せます。':'Look through titles, notes, and tags.'}</p></div><form class="search-form" role="search"><label for="search-input">${ja?'検索語':'Search the notebook'}</label><div class="search-field">${icon('search')}<input id="search-input" name="q" type="search" autocomplete="off" placeholder="${ja?'例えば：数式、データ、読書':'Try “data”, “typography”, or “reading”'}"><kbd>/</kbd></div></form><p id="search-status" class="muted" role="status" aria-live="polite">${ja?'検索語を入力してください。':'Start typing to search.'}</p><div id="search-results" class="post-list"></div><noscript><p>${ja?'検索にはJavaScriptが必要です。':'Search needs JavaScript.'} <a href="${pagePath('writing',lang)}">${ja?'記事一覧を見る':'Browse all writing instead'}</a>.</p></noscript></main>`;
}
export function about(lang='en') {
 const ja=lang==='ja';return `<main id="main" class="wrap page-main"><div class="page-intro"><h1>${ja?'自己紹介':'About'}</h1><p>${ja?'林 寛太 / Kanta Hayashi':'Kanta Hayashi / 林 寛太'}</p></div><div class="prose about-prose"><p>${ja?'東京大学で学びながら、言語モデルの開発に取り組んでいます。関心があるのは、モデルの能力をどう作り、どう確かめるか。事前学習、学習データ、評価について考えています。':"I'm a student at the University of Tokyo working on language models. I'm interested in how we build and evaluate model capabilities, especially pretraining, training data, and evaluation."}</p><p>${ja?'このサイトは、長い実験記録も短いメモも置ける場所にしたいと思っています。コードを書いて確かめたことを、何を試し、何が分かり、何がまだ分からないのかと一緒に残していきます。':"This is a place for long experiment write-ups and shorter notes: what I tried, what happened, and what I still don't know."}</p><h2>${ja?'研究の周りに':'Beyond the experiments'}</h2><p>${ja?'本、映画、漫画、アニメ、批評も好きです。研究の話だけに閉じず、それらについて考える余白も残しておきたいと思っています。':"I also spend time with books, films, manga, animation, and criticism. Not every interesting question has to become a research project. There is room for those detours here too."}</p><h2>${ja?'このサイトについて':'This site'}</h2><p>${ja?'記事は英語を中心に、日本語でも書きます。翻訳がある記事には、切り替えリンクを付けています。':"Most posts will be in English, with some in Japanese. Articles with translations link directly to each other."}</p><p>${ja?'AstroPaperを参考に、文字中心の小さな読書用レイアウトを作っています。広告やアクセス解析は入れていません。':"A small, text-first site derived from AstroPaper. Static pages, no ads, no analytics."}</p><p><a href="${site.github}">GitHub: KantaHayashiAI ↗</a></p></div></main>`;
}
export function lab(posts,lang='en') {
 const ja=lang==='ja';return `<main id="main" class="wrap page-main"><div class="page-intro"><span class="section-kicker">PREVIEW / QA</span><h1>${ja?'表示チェック':'Test the notebook'}</h1><p>${ja?'サンプルは本番公開前の動作確認用です。研究結果ではありません。':'These specimens exercise the publishing system. They are not research results.'}</p></div><div class="qa-grid">${[[ja?'文章と日本語':'Text & Japanese',ja?'英数字との混植、句読点、脚注、長い見出し。':'Mixed scripts, punctuation, footnotes, long headings.'],[ja?'数式とコード':'Math & code',ja?'数式の横スクロール、構文強調、コピーボタン。':'Equation overflow, syntax highlighting, copy buttons.'],[ja?'図とテーブル':'Figures & tables',ja?'狭い画面での表示、画像の拡大、代替テキスト。':'Small screens, click-to-zoom, alternative text.'],[ja?'安全な公開':'Publishing boundaries',ja?'draftとsampleの違い。RSSとサイトマップへの除外。':'Draft/sample separation, RSS and sitemap exclusion.']].map(([t,b])=>`<section><h2>${t}</h2><p>${b}</p></section>`).join('')}</div><h2>${ja?'テスト記事':'Test articles'}</h2><div class="post-list">${posts.filter(p=>p.data.sample).map(p=>postCard(p,lang)).join('')}</div><p class="inline-notice">${ja?'previewはアクセス制限ではありません。公開リポジトリに秘密を書かないでください。':'Preview mode is not access control. Never commit private drafts or credentials to a public repository.'}</p></main>`;
}
export function notFound(lang='en') {return `<main id="main" class="wrap page-main not-found"><span class="section-kicker">404 / A SMALL DETOUR</span><h1>This page took<br>a different path.</h1><p>The note may have moved, or it may still be a draft.</p><a class="text-link" href="/writing/">Browse the notebook ${icon('arrow')}</a></main>`;}
