import test from 'node:test';
import assert from 'node:assert/strict';
import {escapeHtml,escapeJson,safeUrl,postPath,pagePath,visiblePosts,feedPosts,translationOf,readingMinutes} from '../src/lib/content.mjs';
import {headMeta,header,home,articleStart,articleEnd} from '../src/lib/ui.mjs';
import {readPosts,parseSource} from '../scripts/read-content.mjs';
const now=Date.parse('2026-09-19T12:00:00Z');
const p=(d={})=>({id:d.slug??'a',data:{title:'Example',slug:'a',description:'A sample',pubDatetime:'2026-01-01T00:00:00Z',lang:'en',kind:'research',tags:[],draft:false,sample:false,...d},body:'A test'});
test('escape arbitrary title markup',()=>assert.equal(escapeHtml('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;'));
test('script-closing text cannot escape JSON-LD',()=>assert.ok(!escapeJson('</script><script>x</script>').includes('<')));
test('absolute links supported',()=>assert.equal(safeUrl('https://example.com/'),'https://example.com/'));
test('local links supported',()=>assert.equal(safeUrl('/about/'),'/about/'));
test('javascript URLs rejected',()=>assert.equal(safeUrl('javascript:alert(1)'),'#'));
test('protocol-relative URLs rejected',()=>assert.equal(safeUrl('//example.com'),'#'));
test('English post URL',()=>assert.equal(postPath(p()),'/posts/a/'));
test('Japanese post URL',()=>assert.equal(postPath(p({lang:'ja'})),'/ja/posts/a/'));
test('Japanese home URL',()=>assert.equal(pagePath('','ja'),'/ja/'));
test('drafts never become public',()=>assert.deepEqual(visiblePosts([p({draft:true})],{stage:'preview',now}),[]));
test('scheduled articles stay hidden',()=>assert.deepEqual(visiblePosts([p({pubDatetime:'2099-01-01'})],{stage:'preview',now}),[]));
test('sample shows only during preview',()=>assert.equal(visiblePosts([p({sample:true})],{stage:'preview',now}).length,1));
test('sample does not show live',()=>assert.equal(visiblePosts([p({sample:true})],{stage:'live',now}).length,0));
test('real articles show live',()=>assert.equal(visiblePosts([p()],{stage:'live',now}).length,1));
test('RSS always omits sample articles',()=>assert.equal(feedPosts([p({sample:true})],now).length,0));
test('sort uses last modification when supplied',()=>assert.equal(visiblePosts([p({slug:'a'}),p({slug:'b',modDatetime:'2026-09-01'})],{now})[0].data.slug,'b'));
test('translation uses explicit pairing only',()=>{const a=p({translationKey:'x'}),b=p({slug:'b',lang:'ja',translationKey:'x'});assert.equal(translationOf(a,[a,b]),b)});
test('unpaired article has no false translation',()=>assert.equal(translationOf(p(),[p({lang:'ja'})]),null));
test('reading estimate is at least one minute',()=>assert.equal(readingMinutes(''),1));
test('reading estimate includes Japanese',()=>assert.ok(readingMinutes('あ'.repeat(1200))>=3));
test('live article metadata is indexable',()=>{const s=headMeta({path:'/posts/a/'});assert.ok(s.includes('https://kantahayashiai.github.io/posts/a/'));assert.ok(s.includes('content="index, follow"'))});
test('head escapes title injection',()=>assert.ok(headMeta({title:'<script>bad</script>'}).includes('&lt;script&gt;')));
test('post social image uses per-post route',()=>assert.ok(headMeta({post:p()}).includes('/og/posts/en-a.png')));
test('header has accessible name and skip link',()=>{const h=header();assert.ok(h.includes('Skip to content'));assert.ok(h.includes('aria-label="Search"'))});
test('article has one main and article boundary',()=>{const h=articleStart(p(),[],null)+'<p>x</p>'+articleEnd(p());assert.equal((h.match(/<main\b/g)||[]).length,1);assert.equal((h.match(/<article\b/g)||[]).length,1);assert.ok(h.endsWith('</main>'))});
test('sample corpus remains explicitly marked',()=>{const ps=readPosts().filter(x=>x.data.sample);assert.ok(ps.length>=8);assert.ok(ps.every(x=>!x.body.includes('Jev')))});
test('source has an actual draft sentinel',()=>assert.ok(readPosts().some(p=>p.data.draft&&p.data.slug==='draft-sentinel')));
test('both languages have test content',()=>{const ps=readPosts();assert.ok(ps.some(p=>p.data.lang==='ja'));assert.ok(ps.some(p=>p.data.lang==='en'))});
test('all visible demo paths are unique',()=>{const ps=visiblePosts(readPosts(),{now});assert.equal(new Set(ps.map(postPath)).size,ps.length)});
test('actual drafts are absent from home',()=>assert.ok(!home(visiblePosts(readPosts(),{now})).includes('DRAFT MUST')));
test('live publication includes Jev and excludes samples and drafts',()=>{const ps=visiblePosts(readPosts(),{stage:'live',now:Date.parse('2026-09-20T12:00:00Z')});assert.ok(ps.some(p=>p.data.slug==='jev-does-not-play-dice'));assert.ok(ps.every(p=>!p.data.sample&&!p.data.draft))});
test('frontmatter parser returns content separately',()=>{const s=parseSource('---\ntitle: "abc"\nsample: true\n---\nhello');assert.equal(s.data.title,'abc');assert.equal(s.body.trim(),'hello')});
